apiVersion: v1
kind: Pod
metadata:
  labels:
    run: strigus
  name: strigus
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /meu-volume
      name: meu-emptydir
    resources: 
      limits:
        cpu: "0.8"
        memory: "64Mi"
      requests:
        cpu: "0.5"
        memory: "32Mi"
  - image: busybox
    name: busybox
    args:
      - sleep
      - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: meu-emptydir
    emptyDir:
      sizeLimit: "128Mi"
